### ISSUE TITLE
姐姐，反馈个bug

### ISSUE THREAD

**Issue by Angelic47** [Archeb/Candy-Rebirth#13]
winz姐姐~主题在android设备上存在一个bug
回复框第三行点击后会跑到页面外边，无法通过滚动页面的形式拉出，影响正常输入
输入时会被输入法挡住
测试设备: note 8, android 7.1, chrome, 三星输入法
![screenshot_20180420-233014](https://user-images.githubusercontent.com/8847879/39060241-6dd418ce-44f3-11e8-8fc3-9e44dfb51894.jpg)
![screenshot_20180420-233436](https://user-images.githubusercontent.com/8847879/39060251-7231ce2a-44f3-11e8-8a65-fcf7841326bc.jpg)

**Comment by Archeb** [comment]
已知BUG，下个版本修复移动端padding
