### ISSUE TITLE
←◡←

### ISSUE THREAD

**Issue by seestars** [Archeb/Candy-Rebirth#17]
然后Typecho中版本显示1.2（←◡←），对插件依旧不怎么友好的样子啊，cPlayer插件依旧无法显示

**Comment by seestars** [comment]
模版让文章预览功能鬼畜

**Comment by Archeb** [comment]
插件的支持是加上了Typecho原有的header和footer函数调用，使得一些注入这两个函数的插件能够运行（主要是添加js和css之类）
文章预览略坑，我都不知道具体他的实现机制
