### ISSUE TITLE
归档页面问题

### ISSUE THREAD

**Issue by lxyeternal** [Archeb/Candy-Rebirth#23]
你好，我目前使用的就是你的主题，但是由于文章数目多的话，查看起来就会很麻烦，请问如何添加一个归档页面，我在添加的时候模板中没有任何的选项

**Comment by Archeb** [comment]
我没有做归档页面，你可以试试找一些归档页面的插件用

**Comment by lxyeternal** [comment]
> 我没有做归档页面，你可以试试找一些归档页面的插件用

好的，非常感谢你
