### ISSUE TITLE
MathJax错位

### ISSUE THREAD

**Issue by sanaprix** [Archeb/Candy-Rebirth#24]
![image](https://user-images.githubusercontent.com/44078938/51883199-e38cf380-23bc-11e9-939a-47825593bf54.png)
![image](https://user-images.githubusercontent.com/44078938/51883207-ed165b80-23bc-11e9-8264-76d197398b27.png)
MathJax公式错位了，官方主题就没有这个问题，不清楚怎么回事QAQ
页面：typecho.sanapri.cn/articles/2018/5
[typecho.sanapri.cn/articles/2018/5](url)

**Comment by Archeb** [comment]
貌似是mathjax计算公式所需宽度的的时候计算错了...但我不知道怎么修
