### ISSUE TITLE
Pjax 局部刷新后 MathJax 不加载

### ISSUE THREAD

**Issue by sanaprix** [Archeb/Candy-Rebirth#27]
上次 MathJax 错位的问题倒是解决了，这次又遇到了新的问题。

点击文章页面后，需要手动刷新才能加载 MathJax ，并且滚动时新加载出的文章摘要中也没有加载 MathJax 。

![image](https://user-images.githubusercontent.com/44078938/52857951-b766c600-3163-11e9-97b1-eb4ef2e212b4.png)

![image](https://user-images.githubusercontent.com/44078938/52857955-bdf53d80-3163-11e9-834a-4baefea98f5e.png)

问题站：http://typecho.sanapri.cn

OI选手没有接触过前端，请问该如何解决？

**Comment by Archeb** [comment]
已添加MathJax PJAX渲染支持 https://github.com/Archeb/Candy-Rebirth/commit/80f93db773fbb97aec05c3a95a214544d89befc6
请更新m.js文件查看效果
