### ISSUE TITLE
index文章计数问题

### ISSUE THREAD

**Issue by ghost** [Archeb/Candy-Rebirth#3]
你发布的主题里面用的是myPublishedPostsNum和myPublishedCommentsNum，这样在未登录时好像是会显示0的。建议改成PublishedPostsNum和PublishedCommentsNum。

**Comment by Archeb** [comment]
我博客已经发现并且修复了... 还没推送 2333

**Comment by ghost** [comment]
(´･Д･)」你看我发现那么多bug 你女装道歉吧

**Comment by Archeb** [comment]
(都是已知bug 拒绝23333

**Comment by Archeb** [comment]
v1.1 已修复
