### ISSUE TITLE
markdown支持问题

### ISSUE THREAD

**Issue by ghost** [Archeb/Candy-Rebirth#4]
emmm是不是不支持？

**Comment by Archeb** [comment]
支持呀 有的样式 没写而已
( 我 博客 在用的版本修复了部分 放假就推上来

**Comment by ghost** [comment]
那我先去你博客下载css吧(´･Д･)」

**Comment by ghost** [comment]
看了下，发现并不是markdown支持问题，是你css设置了个font-weight: 400=-=

**Comment by ghost** [comment]
还有个问题，建议给<a>添加颜色，不然全黑的分不清

**Comment by Archeb** [comment]
v1.1 已修改部分样式
