### ISSUE TITLE
horwheel在chrome横向收缩页面后无法正常使用

### ISSUE THREAD

**Issue by ghost** [Archeb/Candy-Rebirth#6]
上划下滑操作无效，左右划动也无效

**Comment by Archeb** [comment]
横向收缩小于991px后将转为触屏模式 仅支持移动端的滑动，没有对鼠标滚轮进行响应
已知设计 不认为是bug

**Comment by ghost** [comment]
妈耶这设计本身就是bug吧=-=

**Comment by Archeb** [comment]
至少我觉得正常人在使用电脑浏览器访问的时候不会蛋疼的拖到991px以下去看

**Comment by ghost** [comment]
。。。我在调试竖屏拉取新内容 然后你这玩意直接=-=

**Comment by Archeb** [comment]
竖屏调试请F12使用手机模拟模式

**Comment by ghost** [comment]
我拒绝 我就只⌥⌘I 别的操作我懒 (╯°□°）╯︵ ┻━┻

**Comment by Archeb** [comment]
那就不是我的问题了（

**Comment by ghost** [comment]
emmm我试了下 console不输出东西 玩毛=-=
