### ISSUE TITLE
请问升级后报这个错怎么解决

### ISSUE THREAD

**Issue by sysytemofxxx** [Archeb/Candy-Rebirth#9]
<img width="1030" alt="snipaste_2018-04-16_09-29-31" src="https://user-images.githubusercontent.com/28782855/38786151-b2b118c8-4158-11e8-8e8e-d18930d6edd0.png">

**Comment by Archeb** [comment]
应该不影响使用和设置，下个版本修复

**Comment by sysytemofxxx** [comment]
@Archeb 好的，谢谢，麻烦了。

**Comment by Archeb** [comment]
v1.3已修复
